# Generated by Django 4.0.3 on 2022-03-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('hash_id', models.IntegerField(primary_key=True, serialize=False)),
                ('frequency', models.CharField(max_length=70)),
                ('flag', models.BooleanField()),
            ],
        ),
    ]
